# Generated by Django 5.0.3 on 2024-03-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_memory_status_alter_picture_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
