# Generated by Django 5.0.3 on 2024-04-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_alter_memory_id_alter_picture_id_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='memory',
            new_name='memory_id',
        ),
    ]
